name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/auto-cancel-redundant-job@v1
    - uses: actions/checkout@v2
    - name: Test
      run: swift test --enable-code-coverage --enable-test-discovery
    - name: Generate Coverage Report
      run: |
        curl https://apt.llvm.org/llvm.sh | sudo bash
        export b=$(swift build --show-bin-path) && llvm-cov-12 \
          export -format lcov \
          -instr-profile=$b/codecov/default.profdata \
          --ignore-filename-regex='\.build/' \
          $b/SublimatePackageTests.xctest \
          > info.lcov
    - uses: codecov/codecov-action@v1
      with:
        file: ./info.lcov
